require('dotenv').config();
require('./server/db-conn');
const express = require('express');
const bodyParser = require('body-parser');

const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:false}));
// gives server access to static files generated by running yarn build in client

app.get('/*', (req, res) => {
    res.sendFile('index.html', { root: __dirname });
  });
// the asterisk is very important!! as it allows client side routing
// with react-router or w/e client side routing package you use

const {PORT} = process.env;
app.listen(PORT, () => console.log(`Working like a champ on port ${PORT}`));
